### PR TITLE
Allow unicode characters in passwords

### PR DESCRIPTION
**Pull request by peoplesbeer**
I suggest allowing all unicode characters except some non printable ones (0x00 - 0x1F) in passwords.

### CODE REVIEW

**Comment by mattiaslevin** [comment]
I agree the current regexp is to narrow and needs to be widened.

This is however a can of worms and prefer not to allow not printable characters due to mainly usability issues (e.g. when copying passwords) and potential issues on some platforms, mainly web.

We should allow more characters but:
-Exclude whitespace
-Still have a controlled set of characters 

Can you make a revised suggestion?

Something along:
0021 - 007E
00A1 - 0587

**Comment by peoplesbeer** [comment]
Ok, I still feel that the first suggestion is better. But how about `Pattern.compile("^[\\x21-\\x7E\\xA0-\\xBF\\w]{5,}$", Pattern.UNICODE_CHARACTER_CLASS)`?

- `\\x21-\\x7E` (characters between 0x20 and 0x7E): Included because we want to allow some special characters like !, ", # and so on.
- `\\xA1-\\xBF` : More special characters (let's not discriminate for all who'd like ¡ in their password...)
- `\w`: Matches all characters in any language (because we use the `Pattern.UNICODE_CHARACTER_CLASS` flag).

**Comment by mattiaslevin** [comment]
Ha, you do know even know how to type a ȹ on your computer.

**Comment by peoplesbeer** [comment]
Hmmm, don't know why the build failed but I close it.

**Comment by mattiaslevin** [comment]
It is because of SNAPSHOT dependencies to Mardao. Ola will fixa that today.

**Comment by peoplesbeer** [comment]
Obviously not...

**Pull request merged**
